export default function SendEmailForm() {
    return (

        <div className="flex w-full items-center justify-center py-12 bg-white">
                <div className="w-full mx-auto px-4 py-8 sm:px-6 sm:py-16 md:py-24">
                    <div className="flex flex-col items-start gap-4 lg:col-span-2">
                        
                        <div className="relative w-full flex justify-center md:justify-start">
                                <div className="relative"><img src="https://cdn.shadcnstudio.com/ss-assets/blocks/marketing/contact-us/image-5.png" alt="Modern office hallway" className="rounded-md max-md:hidden md:h-[42rem] md:w-[40rem] lg:w-full" /></div>
                            <div data-slot="card" className="bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm border-none md:absolute md:top-1/2 md:right-0 md:w-3/4 md:max-w-128 md:-translate-y-1/2"><a href="#">
                                    <div data-slot="card-header" className="@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-2 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6">
                                        <div data-slot="card-title" className="font-semibold text-2xl">Send us a message</div>
                                        <div data-slot="card-description" className="text-muted-foreground text-base">Get in touch with us for any inquiries or support. We&apos;re here to assist you and ensure your experience is exceptional.</div>
                                    </div>
                                    <div data-slot="card-content" className="px-6">
                                        <form className="space-y-6">
                                            <div className="flex w-full flex-wrap gap-6">
                                                <div className="w-auto grow space-y-2"><label data-slot="label" className="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50" htmlFor="name">Your Name</label><input type="text" data-slot="input" className="file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive h-10" placeholder="Enter your name" id="name" required /></div>
                                                <div className="w-auto grow space-y-2"><label data-slot="label" className="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50" htmlFor="email">Your Email</label><input type="email" data-slot="input" className="file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive h-10" placeholder="Enter your email" id="email" required /></div>
                                            </div>
                                            <div className="space-y-2"><label data-slot="label" className="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50" htmlFor="subject">Subject</label><input type="text" data-slot="input" className="file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive h-10" placeholder="Enter subject" id="subject" required /></div>
                                            <div className="space-y-2"><label data-slot="label" className="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50" htmlFor="message">Message</label><textarea data-slot="textarea" className="border-input placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 flex field-sizing-content min-h-16 w-full rounded-md border bg-transparent px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm h-16 resize-none" placeholder="Type your message here..." id="message" required></textarea></div><button data-slot="button" className="focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-6 has-[>svg]:px-4 w-full rounded-lg text-base" type="submit">Get Free Quote</button>
                                        </form>
                                    </div>
                                </a>
                                <div data-slot="card-footer" className="flex items-center px-6 [.border-t]:pt-6"><a href="#"></a>
                                    <p className="text-muted-foreground text-lg"><a href="#">I understand that my data will be hold securely in accordance with the !-- -- </a><a href="#" className="text-card-foreground font-semibold underline">privacy policy</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-6 sm:px-6"><br /></div>
            </div>

    )
}