import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import axios from 'axios'
import React, { useEffect, useState } from "react";

export const fetchProducts =  createAsyncThunk('products/fetchProducts', 
    async () => {
        const response = await axios.get('https://fakestoreapi.com/products')
        return response.data;
})


// Define the initial state
const initialState = {
  products: [],
  status: 'idle', // 'idle' | 'loading' | 'succeeded' | 'failed'
  error: null,
};
const productSlice = createSlice({
  name: 'products',
  initialState,
  reducers: {
    // Add any synchronous reducers here if needed (e.g., sortProducts, filterProducts)
  },
  // Handle actions generated by createAsyncThunk
  extraReducers: (builder) => {
    builder
      .addCase(fetchProducts.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchProducts.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.products = action.payload; // Add fetched products to the state
      })
      .addCase(fetchProducts.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message;
      });
  },
})

// Export the reducer
export default productSlice.reducer